[package]
name = "shuo"
version = "1.1.0"
edition = "2024"
description = "Crate that just shuo — info!, error!, error_out!, and *_or_error_out! macros."
license = "MIT"
repository = "https://github.com/jhuanglululu/shuo"
readme = "README.md"
keywords = ["logging", "log", "println", "macro"]
categories = ["development-tools::debugging"]
